---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: document
  path: src/data/site.json
  label: Site Settings & Authors
- type: directory
  path: src/content/items
  label: Items
  create: documents
  match: "**/*"
  templates:
  - page
upload_dir: src/assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - NODE_ENV=development
  - ELEVENTY_ENV=staging
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:erbium
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run staging
